// Typelizer digest 2576001fdc5f841284d153592e157bde
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Article} from '.'

type ArticleDetail = Article & {
  body: string;
}

export type { ArticleDetail };
