// Typelizer digest 16a65fe9b3434adaade06ec02753d35f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Article = {
  id: number;
  title: string;
  author_name: string;
  comments_count: number;
  created_at: string;
}

export type { Article };
