// Typelizer digest 24bf1884bf84c61e356ef8a632a35822
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Comment = {
  id: number;
  body: string;
  author_name: string;
  created_at: string;
}

export type { Comment };
