// Typelizer digest 0e10bc81efa137ad7ecdef92bdc0aaf4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Article} from '.'

type Engagement = {
  total_articles: number;
  total_comments: number;
  most_commented: Array<Article>;
}

export type { Engagement };
